
platform :ios, '13.0'
use_frameworks!

target 'Notex' do
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Analytics'
  pod 'Firebase/Storage'
  pod 'GoogleSignIn'
end
